const productList = [
  '<h3>Atta/Flour</h3>',
  'Aashirwad Chakki Atta 5Kg',
  'Ashirwaad Chakki Atta 10kg',
  'Ashirwaad Select 10kg',
  'Ashirwaad Select 5kg',
  'Deep Bajari Flour 907g',
  'Deep Besan 907g',
  'Deep Bhakri Flour 907g',
  'Deep Dhokla Flour 907g',
  'Deep Jowar Flour 907g',
  'Deep Kuttu Flour 907g(upwas)',
  'Deep Ladu Besan 907g',
  'Deep Maida 907g',
  'Deep Rice Flour 907g',
  'Deep Singora flour 907g(upwas)',
  'Garewal Atta 10Kg',
  'Garewal Atta 5kg',
  'Grewal Besan 1kg',
  'Grewal Chakki atta 5kg',
  'Merchant Spice Rice Flour 1kg',
  'Merchant Spices Maida 1kg',
  'Parijat Bhakri Flour 500gm',
  'Pilsbury Chakki Atta 10Kg',
  'Pilsbury Chakki Atta 5Kg',
  'Pilsbury Gold Atta 10kg',
  'Pilsbury Gold Atta 5kg',
  'Pilsbury Multigrain 5kg',
  'Sahyadri Jowar Flour 1kg',
  'Sakas Rice Flour 1Kg',
  '<h3>Beauty Products</h3>',
  'Ayur Rajasthani Dark Brown Mehendi',
  'Bajaj Almond Drops 300ml',
  'Bajaj Almond Drops 50ml',
  'Clean & Clear Foaming Face wash 100ml',
  'Dabur Red Toothpaste',
  'Dabur Rogan Badam Oil 50ml',
  'Dabur Vatika Hair Oil 250ml',
  'Fair and Lovely HD Glow 80g',
  'Neha Heena',
  'Parachute Coconut Oil 200ml',
  'Parachute Coconut Oil 500ml',
  'Patanjali Saundarya Aloe Vera Gel 150ml+Free Dant Kanti toothpaste',
  'Ponds Magic Talcum Powder 400g',
  "Pond's White Beauty face wash 100g",
  'Ponds white beauty100g',
  'Rose Water',
  'Shilpa Bindi black size 7',
  '<h3>Biscuits</h3>',
  'Bikanoo Suji Rusk 600g',
  'Britania Bour Bon 390g',
  'Britania Marie Gold 150g',
  'Britania Nutri Choice 150g',
  'Britania Suji Rusk 610g',
  'Britannia Cake Rusk 240g',
  'Britannia Digestive Sugar Free 200g',
  "Cherab's Almond Cookies 300gm",
  "Cherab's Besan Cookies 300gm",
  "Cherab's Butter Kaju Cookies 300gm",
  "Cherab's Cherry Cake Rusk 900Gm",
  "Cherab's Coconut Cookies 300gm",
  "Cherab's Pista Cookies 300gm",
  "Cherab's Vegeterian Atta Biscuit 1kg",
  "Cherab's Vegeterian Cherry Cake Rusk 900Gm",
  "Cherab's Vegeterian Nankatai 300gm",
  'Deep Khari Original 400g',
  'Deep Methi Khari 200g',
  'Deep nankhatai 400g',
  'Goodday Butter 720g Value pack',
  'Goodday Butter 75g',
  'Goodday Cashew 720g Value pack',
  'Goodday Cashew 75g',
  'Monaco Biscuits 316gm',
  'Parle G 376g',
  'Parle G 799g',
  'Parle Hide & Seek 412g',
  '<h3>Chinese</h3>',
  'Ajinomoto 50G',
  'Chings Chilli Vinegar',
  'Chings dark Soy Sauce',
  'Chings Green Chilli Sauce',
  'Chings Red Chilli Sauce',
  'Chings Schezwan Chutney 250g',
  'Chings Schezwan Sauce - Stir Fry',
  '<h3>Coconut</h3>',
  'Coconut Dessicated-Fine 500gm',
  'Coconut Slice 200gm',
  'Pattu Coconut Half 170g',
  '<h3>Dairy/Paneer</h3>',
  'Nanak Khoa',
  'Nanak Malai paneer cubes 400g',
  'Nanak Paneer Cubes fried 400g',
  'Sai Shree Amrakhand 270g',
  'Sai Shree Paneer',
  'Sai Shree Shrikhand 270g',
  'Sai Shree Yoghurt 1kg',
  'Sai Shree Yoghurt 5kg',
  "Sharma's Paneer",
  "Sharma's Yoghurt 2kg",
  'Village organic Yoghurt 2kg',
  'Village Paneer',
  'Village pot set Yoghurt 2kg',
  'Village Pot set Yoghurt 5kg',
  '<h3>Drinks</h3>',
  'Keshav Badam Milk 250ml',
  'Limca 300ml Can 300ml',
  'Mazza mango Drink 600ml',
  'Mazza mango Drink mini bottle 200ml',
  'Real Mix Fruit Juice 1lt',
  'SS Salted lassi',
  'Thumbs Up can 300ml',
  'Thumbs Up mini bottle 200ml',
  '<h3>Dryfruits & Peanuts</h3>',
  'Cashew Lg Pcs 250g',
  'HS Raisins-Golden 250g',
  'Pattu Cashew Raw 250g',
  'Pattu Dates 500g',
  'Pattu Peanut blanched 250g',
  'Pattu Peanuts Raw Large 500g',
  'Pattu Peanuts Raw Lg 250g',
  'Pattu Peanuts Raw Small 1Kg',
  '<h3>Extra</h3>',
  'Tongue Cleaner',
  '<h3>Frozen Fruits</h3>',
  'Chickoo Slices 312g',
  'Deep Green Mango 340g',
  'Vadilal Alphonso Mango slices 312g',
  'Vadilal Green Mango 312g',
  '<h3>Frozen Paratha/Naan/Bhatura</h3>',
  'Deep Aloo Paratha 4pcs',
  'Deep Bhatura (5 pcs)',
  'Deep Garlic Naan (4pcs)',
  'Deep Home-style Paratha Family Pack (20pcs)',
  'Deep Methi Paratha(5pcs)',
  'Deep Mix Vegetable Paratha 4 Pcs',
  'Deep Paneer Paratha (4pcs)',
  'Deep Tandoori Naan (5pcs)',
  'Family pack Deep Tandoori Naan (16pcs)',
  'Haldiram Aloo Achari Paratha 4pcs',
  'Haldiram Aloo Paratha 4pcs',
  'Halidiram Gobi Paratha 4pcs',
  'Katoomba Paratha (30pcs)',
  'Katoomba Wholemeal Roti Paratha(25pcs)',
  'Katoombaa Chapati 30 Pcs',
  'Kawan Chapati 30pcs',
  'Kawan Plain Paratha (25pcs)',
  'Malabar Treat Malabar Parotta 908g',
  'Malabar Treat Malabar Wheat Parotta 908g',
  'Pattu Roti Paratha 30Pcs',
  '<h3>Frozen Snacks</h3>',
  'Ashoka Punjabi Samosa 1875g(25pcs)',
  'Bhagwati Muthia 340g',
  'Deep Mathia 200g',
  'Deep Moong Dal Kachori 708g(25pcs)',
  'Deep Potato Cocktail Samosa 425g(50pcs)',
  'DeepVegie burger 283g',
  'Haldiram Aloo tikki 420g (8pcs)',
  'Hot Wok Spring Roll 255g',
  'Sabrini Asli Punjabi Samosa 1.875kg(25pcs)',
  'Udupi Idli 255g',
  'Udupi Masala Dosa 397g(4 Pcs)',
  'Udupi Mendu Vada 233g',
  'Udupi Sambar(283g)',
  'Udupi Utthapum 354g(4pcs)',
  '<h3>Frozen VEGGIES</h3>',
  'Deep Arvi 340g',
  'Deep Baby Bhindi 340g',
  'Deep Bhindi Cut(Okra) 340g',
  'Deep Drumsticks 340g',
  'Deep Dudhi 340g',
  'Deep Green Peas 907g',
  'Deep Karela 340g',
  'Deep Methi 340g',
  'Deep Parwal 340g',
  'Deep Premium Coconut slices 340g',
  'Deep Punjabi Tinda 340g',
  'Deep Red Pearl Onion 340g',
  'Deep Sambhar Mix 340g',
  'Deep Suran 340g',
  'Deep Surti Undhiu Mix 340g',
  'Deep Tindora 340g',
  'Sunfeast Grated coconut 400g',
  'Vadilal Amla 312g',
  'Vadilal Avial Mix',
  'Vadilal Cassava Cuts 312g',
  'Vadilal Chauli String Beans 312g',
  'Vadilal Green chillies 312g 10% extra',
  'Vadilal Kala Chana 312g',
  'Vadilal Moth Beans 312g',
  'Vadilal Ratalu 312g',
  '<h3>Ghee/Oil</h3>',
  'Britannia Cow Ghee 902g',
  'Castor Oil 200ml',
  'Deep Cow Ghee 946ml',
  'Dhara Sunflower oil 2lts',
  'Dhara Vegetable Oil 2lts',
  'Idhyam Sesame/Gingelly Oil 2lts',
  "Miller's Sunflower Oil 5lts",
  'Nanki Mustard oil 500ml',
  'Verka Ghee 1Lt',
  '<h3>Idli Batter</h3>',
  'Idli Batter',
  'Keshav Idli Batter 1kg',
  'Sai Shree Idli Dosa Batter 1kg',
  '<h3>Medicine</h3>',
  'Dabur Hajmola',
  'Dabur Honitus 100ml',
  'Dabur Pudin Hara 30ml',
  'Dabur Triphala Churna 120g',
  'Kayamchurna 100g',
  '<h3>Papad</h3>',
  'Bansi Color Fryums 200G',
  'Bansi Fry me 200G',
  'Eastern Plain Papad 200g',
  'Lijjat Pappad',
  '<h3>Paste</h3>',
  'Deeep Ging Garlic 723g',
  'Deep Garlic Paste 283Gm',
  'Deep Garlic Paste 723g',
  'Deep Ginger Garlic Paste 283Gm',
  'Deep Ginger Paste 283Gm',
  'Deep Ginger Paste 723g',
  'Katoomba Garlic Paste 1kg',
  'Katoomba Ginger Garlic Paste 1kg',
  'Larich Curry Paste 350g',
  '<h3>Pickle/Chutney/Sauces</h3>',
  'Deep Chundo 35g',
  'Deep Hot Mango Pickle 740g',
  'Deep Sweet Lime Pickle 340g',
  'Deep Tamarind Date Chutney 227g',
  'Deep Tamarind Date Chutney 510g',
  'Maggi Hot and Sweet 500g',
  'Maggi Rich Tomato 500g',
  'Mirch Masala Pani Puri Concentrate 220g',
  'Pattu Sandwich Spread 280g 1+1',
  'Priya Cut Mango Pickle300g(with garlic)',
  'Priya Mango Pickle 300g(Avakaya with garlic)',
  'Priya Mix veg pickle 300g(with garlic)',
  'Tamarind Seedless',
  '<h3>Pooja</h3>',
  'Cotton Wicks',
  'Gnapati Pooja samagri set',
  'He Fragrance Agarbatti',
  'Hem 5 agarbatti',
  'Hem Gulab Agarbatti',
  'Hem Lavendar agarbatti',
  'Hem Love Agarbatti',
  'Hem Meditation Agarbatti',
  'Hem Mogra Agarbatti',
  'Hem Rose musk',
  'Hem White Musk',
  'Sehaj White Janeu',
  'Vibhuti pooja item',
  'Vinayak Sandal Dhoop',
  '<h3>Products from Maharashtra-Chutney,Powder,premix</h3>',
  'Bedekar Liniseed Chutney',
  'Karala Chutney 100g',
  'Marathi Swad Dink Powder 200g',
  'Marathi Swad Javas Chutney 100g',
  'Marathi Swad Jeshthmadh Powder 100g',
  'Marathi Swad Vada Paav Chutney 100G',
  'Parijat Metkut 100g',
  '<h3>Products from MaharashtraFlour</h3>',
  'Parijat Saguti Vade Flour 500g',
  '<h3>Products from Maharashtra-Flour</h3>',
  'Marathi Swad Kulith Pith 250G',
  'Parijat Bajari Flour 500g',
  'Parijat Infant Porridge mix 200g',
  'Parijat Paushthik Bhakri Flour 500g',
  'Parijat Sattu Flour 200g',
  'Parijat Thalipeeth Bhajani 500g',
  'Parijat Upwas Bhajani 250g',
  'Saguti Vade Flour 500G',
  'Sakas Upwas Bhajani 500g',
  'Soham Udyog Lokwan Atta 5kg',
  '<h3>Products from Maharashtra-Frys</h3>',
  'Crispy Kurdai 200G',
  'Crispy onion rings',
  'Nachani Papad',
  'Poha Mirgund 200g',
  'Potato Papad Red Chili 200G',
  'Potato Salli 200g',
  'Sabudana Papadi Plain 200G',
  'Sandge',
  '<h3>Products from Maharashtra-Ghee</h3>',
  'Chitale Cow ghee 1lt',
  '<h3>Products from Maharashtra-Masala</h3>',
  'Kalyan Pani Puri Masala',
  'Marathi Swad Kanda Lasun Masala',
  'Marathi Swad Malvani Masala',
  'Parijat Goda masala 100g',
  'Parijat Magic masala100g',
  'Prakash Khandeshi Masala',
  'Prakash Kolhapuri Bharli Vangi 25g',
  'Prakash Kolhapuri Chicken Rasa Masala 25g',
  'Prakash Malvani Fish Rassa masala',
  'Prakash Misal Rassa Masala',
  'Prakash Shev Bhaji Masala',
  'Sakas Kala/Goda Masala 100g',
  '<h3>Products from Maharashtra-Pickle</h3>',
  'Bedekar Lime Chilli Pickle',
  'Bedekar mango pickle',
  '<h3>Products from Maharashtra-Pulp</h3>',
  'Desai Bandhu Alphonso mango Pulp (machine made)',
  'Desai Bandhu Alphonso mango Pulp with Chunks(Hand made)',
  '<h3>Products from Maharashtra-Ready to Eat</h3>',
  'Devashree Ready to eat ambadi Bhaji',
  'Devashree Ready to Eat Patra Bhaji',
  'Kalyan Misal Tarri',
  'Marathi Swad Aluchi(patra) Bhaji',
  '<h3>Products from Maharashtra-Rice</h3>',
  'Sahyadri Ambemohar Rice 5kg',
  'Sahyadri Indrayani Rice 5kg',
  'Sahyadri Kolam Rice 5kg',
  '<h3>Products from Maharashtra-Snacks</h3>',
  'Chitale Bandhu Bakarwadi',
  'Ganesh Bhel 250g',
  'Kalyan Farsan',
  'Kalyan Pani Puri',
  'Sohum Udyog Rajgira roll',
  '<h3>Products from Maharashtra-Souring & Syrups</h3>',
  'Yojak Amsul 200g',
  'Yojak Kaire Panhe 500ml',
  'Yojak Kokam Agal 500ml',
  'Yojak Kokam Syrup 500ml',
  '<h3>Products from Maharashtra-Sweets</h3>',
  'Kalyan Ready To eat Puran',
  'Lonawala Shengdana Wadi 200g',
  'Mahabaleshwar Jelly Sweet',
  'Marathi Swad Ready to Eat Puran',
  '<h3>Pulses</h3>',
  'Black Eye Beans 1kg(Lobia) 1kg',
  'Chick Pea Large 1kg',
  'Chick Peas Kabuli 1Kg',
  'Cranberry Beans',
  'Masoor daal 907g',
  'Masoor Gota 1kg',
  'Masoor Whole 1kg',
  'Moong Beans Berken 1kg(whole)',
  'Moong Dal 907Gm',
  'Moong Dal Chilka 907G',
  'Moth Beans 907g',
  'Red Kidney Bean Light 1kg',
  'Red Kidney Beans Dark 1kg (Rajma)',
  'Roasted Channa 400Gm',
  'Roasted Gram Split 1kg',
  'Soy Chunks Nutrela 1Kg',
  'Soya chunks mini 200g',
  'Soya Granules 200g',
  'Soya wadi 200g',
  'Toor Daal 1kg',
  'Toor Dhal 1kg',
  'Tyson Chick Pea 1kg',
  'Urad Daal 907g',
  'Urad Dal Chilka 907g',
  'Urad Gota 1kg',
  'Urad whole black',
  'Yellow Split Peas 1Kg',
  '<h3>Ready to eat</h3>',
  'Gits Dahi Vada 500g',
  'Gits Gulab Jamun 500g',
  'Gits Handvo 500g',
  'Gits Khaman Dhokla 500g',
  'Gits Khatta Dhokla 500g',
  'Gits Medhu Vada 500g',
  'Gits Nylon Khaman 500g',
  'Gits Rava Dosa 500g',
  'Gits Rava Idli 500g',
  'Gits Upma 500g',
  'Maggi masala Noodles 420g',
  'Shan Badam Kheer',
  '<h3>Rice,Poha,Murmura</h3>',
  'Balaji Idli Rice 5kg',
  'Balaji Sona Masoori 5kg',
  'Bansi Murmura 400g',
  'Bansi Poha Medium 1.81kg',
  'Bansi Poha Thick 907g',
  'Dawaat Biryani Basmati Rice 5kg',
  'Deep Poha Super Thin 1.81kg',
  'Deep Poha Super Thin 907g',
  'Deep Poha Thin(Medium)907g',
  'Freshco Basmati Everday Rice 5kg',
  'Freshco extra long grain basmati Rice 5kg',
  'Har Roz Basmati Rice 5kg',
  'HS Red Rice 5kg',
  'India Gate Basmati Classic Rice 5kg',
  'India Gate Basmati Super 5Kg',
  'India Gate Sella Golden Basmati Rice 5kg',
  'India Gate Sella White Basmati Rice 5kg',
  'India Gate Sona Masoori 25kg',
  'India Gate Sona Masoori 5kg',
  'Ponni Parboiled Rice 5kg',
  'Ponni Rice 5kg',
  '<h3>Salt/Sugar/Micellaneous</h3>',
  'Baking Powder 150g',
  'Bi Crab Soda',
  'Black Kokum 400g',
  'Black Salt Powder 100g',
  'Brown Sugar 1kg',
  'Chandan mix mouthfreshner',
  'Dabur Honey 300g',
  'HS Saffron Food Color 50g',
  'HS Tandoori Color',
  'Kashmiri Saffron',
  'Kewra Essence 25ml',
  'Kozhi Kodens Jaggery Powder 1kg',
  'LG Hing 50g',
  'Pineapple Essence 25ml',
  'Punjabi Gur 907g',
  'Raw Sugar 1kg',
  'Round Jaggery 1kg',
  'Sendhav Salt 100g(Upwas)',
  'Tamarind Concentrate 227Gm',
  'Tata Salt 1kg',
  'Udupi Jaggery Powder 454g',
  'Vandevi Hing 50g',
  '<h3>Snacks</h3>',
  'Haldiram Channa Dal 200g',
  'Bansi Puri for bhel 400g',
  'Budhani Potato Mixtrure 120g',
  'Budhani Potato waffers 165g',
  'Deep Bajri Khakhara',
  'Deep Fafda 350g',
  'Deep Masala Khakhara',
  'Deep Methi Khakhara',
  'Deep orginal Khari',
  'Deep Orignal Khakhara',
  'Deep Papdi',
  'Deep Papdi 350g',
  'Deep Ratlami sev',
  'Deep Ratlami sev 340g',
  'Garvi Gujrati Bhel Mix 285g',
  'Garvi Gujrati Corn Chiwda 285g',
  'Garvi Gujrati Dry Kachori 285g',
  'Haldiram Aloo Bhujia 200g',
  'Haldiram Bhujia Sev 150g',
  'Haldiram Falahari chiwda 150g',
  'Haldiram Moong Daal 200g',
  'Haldiram Nimbu Masala 200g',
  'Haldiram Pani Puri 240g',
  'Haldiram Plain Bhujia 200g',
  'Haldiram Soya Sticks 150g',
  'Haldiran Boondi 350Gm',
  'Kemchho Dry Fruit Samosa 270g',
  'Kemcho Fulwadi 270g',
  'Kemcho Methi Puri 270g',
  'Kemcho Navratna Mix 270g',
  'Kemcho Nylon Sev 270g',
  'Kemcho Sandwich Bakarwadi 270g',
  'Kemcho Sweet Shankarpare 270g',
  'Kemcho Tea time Puri 270g',
  'Khamang Cornflakes Chiwda 250g',
  'Khamang Poha Chiwda 250g',
  'Khamang Potato Chiwda',
  'Kurkure Masala Munch 95g',
  'Lays Flirty Tomato 52g',
  'Lays Magic Masala 52g',
  'Malabar Treat Banana Chips 200g',
  'Malabar Treat Bittergourd chips 200g',
  'Malabar Treat Butter Murukku 170g',
  'Malabar Treat Malabar Mixture 400g',
  'Malabar Treat Tapioca Chips 150g',
  'Mirch Masala Mumbai Mix340g',
  'Mirch Masala Aloo Upvas Chevda 340g',
  'Mirch Masala Indori Bhujia 340g',
  'Mirch Masala Katta Mitha 340g',
  'Mirch Masala Peanut Bhujia 340g',
  'Mukhwas Jeera Khakra 500g',
  'Mukhwas Masala Khakra 500g',
  'Mukhwas Methi Khakra 500g',
  'Mukhwas Plain Khakra 500g',
  "Sheridan's Hot Murukku 200g",
  "Sheridan's Hot Sev 200g",
  "Sheridan's Hot Sev Mixture 280g",
  "Sheridan's Murukku 200g",
  "Sheridan's Sev 200g",
  'Udupi Andhra Mixture',
  'Udupi Banana Chips 200g',
  'Udupi Kerela Mixture',
  'Udupi Rice Murukku',
  'Udupi Thatai Murukku',
  '<h3>Sooji/Rava/sago/moraiya</h3>',
  'Bambinoo Vermicelli 800g',
  'Dalia 907g',
  'Deep Sooji Coarse 1.81kg',
  'Deep Sooji Coarse 907g',
  'Deep Sooji Farina 1.8kg',
  'Idli Rava 1kg',
  'Merchant Spices Sooji Coarse 1kg',
  'Moraiyo 500g',
  'Roated Sooji 1kg',
  'Sago 1kg',
  'Shan Roasted Vermicelli 150g',
  '<h3>Spices</h3>',
  'Coriander Seeds 400g',
  'Cummin Seeds 1kg',
  'Cummin Seeds 250g',
  'Curry Powder Unroasted 500g',
  'Cuury powder-Jafna 500g',
  'Deep Black Cardomom 100gm',
  'Deep Cumin Powder 400g',
  'Deep Garam Masala 200Gm',
  'Deep Garam Masala 400g',
  'Deep Garam Masala 800Gm',
  'Deep Grn Cardamom Whl200Gm',
  'Deep Mustard Seed 400g',
  'Deep Sesame Seeds 200Gm',
  'Deep Spi Black Pepper Whl 400Gm',
  'Deep Spi Cardamom Powder 100g',
  'Deep Spi Cinnamon Powder 100Gm',
  'Deep Spi Cinnamon Stick 200G',
  'Deep Spi Coriander Cumin powder 400g',
  'Deep Spi Coriander Cumin Powder 800G',
  'Deep Spi Cumin Powder 200g',
  'Deep Spi Cumin Seeds 200Gm',
  'Deep Spi Green Cardamom Whole 100Gm',
  'Deep Spi Mustard Seeds 200Gm',
  'Deep Turmeric Powder 200Gm',
  'Deep Turmeric Powder 400Gm',
  'Deep whole Garam Masala 200g',
  'Eastern Kashmiri Chilli 100g',
  'Eastern Red Chilli Hottest 100g',
  'Everest Chole Masala',
  'Everest Kitchen King 100g',
  'Everest Pani Puri Masala 100g',
  'Everest Royal Garam Masala 100g',
  'Everest Sabji Masala 100g',
  'Everest Sambhar Masala',
  'Everest Shahi Paneer Masala 100g',
  'Ginger Powder200Gm',
  'HS Black Salt Powder',
  'HS Galangal 100g',
  'HS Star Annise Whole 100g',
  'Kali Jeeri 100g',
  'Katoomba Red Chilli Powder (Xtra Hot) 500g',
  'Katri Gum 100Gm',
  'Mace Powder 100Gm',
  'Mangal Rajma Masala',
  'Mangal Tandoori Masala',
  'Mangal Vindaloo Masala',
  'MDH Chat masala 100g',
  'MDH Deggi Mirch Powder 100g',
  'MDH Garam Masala 100g',
  'MDH Kasoori Methi 25g',
  'MDH Pav Bhaji Masala 100g',
  'MDH Tea masala 35g',
  "Mother's Fried Onion Flakes 400g",
  'Panch Phoran 100g',
  'Pattu Ajwain Seeds 100g',
  'Pattu Amchur Powder 100g',
  'Pattu Bay Leaves 100g',
  'Pattu Black Pepper 200g',
  'Pattu Chilly Round 200g',
  'Pattu Cloves Whole 100Gm',
  'Pattu Coriander Powder 100g',
  'Pattu Coriander Powder 500g',
  'Pattu Fennel Seeds 100g',
  'Pattu Fennel Seeds 200g',
  'Pattu Fenugreek seeds 100g',
  'Pattu Fenugreek Seeds 200g',
  'Pattu Kashmiri Chilli Pdr 500g',
  'Pattu Nutmeg Powder 100g',
  'Pattu Poppy seesds white 100g',
  'Pattu Sesame seedes white 250g',
  'Pattu Shah Jeera 100Gm',
  'Shan Bihari Kebab masala',
  'Shan Biryani Masala',
  'Shan Butter Chicken Masala',
  'Shan Chana Masala',
  'Shan Chapli Kebab Masala',
  'Shan Chicken Masala',
  'Shan Chicken Tandori Masala',
  'Shan Chicken Tikka Masala',
  'Shan Curry Powder',
  'Shan Fried Chops/Steak Masala',
  'Shan Haleem Masala',
  'Shan Karahi Masala',
  'Shan Keema Masala',
  'Shan Korma Masala',
  'Shan Malay Biryani Masala',
  'Shan Nihari Masala',
  'Shan Punjabi Yakhni Pilau Masala',
  'Shan Seekh Kebab Masala',
  'White Pepper Powder 100Gm',
  '<h3>Sweets</h3>',
  'Aam Papad',
  'Chitale Bandhu Soan Papdi(Mango)200g',
  'Chitale Bandhu Soan Papdi(Orange) 200g',
  'Deep Kesar Mango Pulp',
  'Haldiram Gulab Jamun 1kg',
  'Haldiram Rasgulla 1kg',
  'Keshav Mix Sweets',
  'Keshav Motichoor Laddu 260g',
  'Nanak Kaju katli',
  'Nanak Kalakand 400g',
  'Nanak Rasmalai',
  '<h3>Tea/Coffee/Health Drink</h3>',
  'Bourn Vita 500g',
  'Bru Super Strong Coffee 500G',
  'Girnar Cardamom chai premix',
  'Girnar Masala Chai premix',
  'Red Label 450g',
  'Red Label Nature Care 250g',
  'Taj Mahal 450g',
  'Wagh Bakri 1kg',
  'Wagh Bakri 500g',
  'Wagh Bakri Masala Tea 250g',
];
