const productList = [
  '<h3>Entertainment</h3>',
  'Super TV(Indian Channels, English and Hinid Movies and lots more - Special Price)',
  '<h3>SNACKS (Sheridans)</h3>',
  'Sheridans Hot Sev Mixture 280g',
  'Sheridans Hot Sev 200g',
  'Sheridans Sev 200g',
  'Sheridans Hot Murukku 200g',
  'Sheridans Murukku 200g',
  '<h3>SNACKS (Garvi Gujrat)</h3>',
  'Garvi Gujrati Bhel Mix 285g',
  'Garvi Gujrati Dry Kachori 285g',
  'Garvi Gujrati Corn Chiwda 285g',
  '<h3>SNACKS (Malabar Treat)</h3>',
  'Malabar Treat Banana Chips 200g',
  'Malabar Treat Bittergourd chips 200g',
  'Malabar Treat Butter Murukku 170g',
  'Malabar Treat Malabar Mixture 400g',
  'Malabar Treat Tapioca Chips 150g',
  '<h3>SNACKS (Deep)</h3>',
  'Deep Fafda 350g',
  'Deep Papdi 350g',
  'Deep Ratlami sev 340g',
  'Deep Bajri Khakhara 200gm',
  'Deep Masala Khakhara 200gm',
  'Deep Methi Khakhara 200gm',
  'Deep orginal Khari 200gm',
  'Deep Orignal Khakhara 200gm',
  '<h3>SNACKS (Kemcho)</h3>',
  'Kemchho Dry Fruit Samosa 270g',
  'Kemcho Methi Puri 270g',
  'Kemcho Nylon Sev 270g',
  'Kemcho Sweet Shankarpare 270g',
  'Kemcho Tea time Puri 270g',
  'Kemcho Fulwadi 270g',
  'Kemcho Navratna Mix 270g',
  'Kemcho Sandwich Bakarwadi 270g',
  'Kemcho Dry fruit Kachori 270g',
  '<h3>SNACKS (Budhani)</h3>',
  'Budhani Potato Mixtrure 120g',
  'Budhani Potato waffers 165g',
  '<h3>SNACKS (Mirch Masala)</h3>',
  'Mirch Masala Aloo Upvas Chevda 340g',
  'Mirch Masala Indori Bhujia 340g',
  'Mirch Masala Katta Mitha 340g',
  'Mirch Masala  Mumbai Mix340g',
  'Mirch Masala Peanut Bhujia 340g',
  '<h3>SNACKS (Haldiram)</h3>',
  'Haldiram Bhujia Sev 150g',
  'Haldiram Falahari chiwda 150g',
  'Haldiran Boondi 350Gm',
  'Haldiram Aloo Bhujia 200g',
  'Haldiram Moong Daal 200g',
  'Haldiram Plain Bhujia 200g',
  'Haldiram Channa Dal 200g',
  'Haldiram Nimbu Masala 200g',
  'Haldiram Soya Sticks 150g',
  '<h3>SNACKS (Khamang)</h3>',
  'Khamang Cornflakes Chiwda 250g',
  'Khamang Poha Chiwda 250g',
  'Khamang Potato Chiwda',
  '<h3>SNACKS (Kurkure/Lays)</h3>',
  'Kurkure Masala Munch 95g',
  'Lays Flirty Tomato 52g',
  'Lays Magic Masala 52g',
  '<h3>SNACKS (Mukhwas)</h3>',
  'Mukhwas Plain Khakra 500g',
  'Mukhwas Masala Khakra 500g',
  'Mukhwas Methi Khakra 500g',
  'Mukhwas Jeera Khakra 500g',
  '<h3>SNACKS (Pani puri/Bhel)</h3>',
  'Bansi Puri for bhel 400g',
  'Haldiram Pani Puri 240g',
  '<h3>SNACKS (Udupi)</h3>',
  'Udupi Banana Chips 200g',
  'Udupi Andhra Mixture 340g',
  'Udupi Kerela Mixture 340g',
  'Udupi Rice Murukku 340g',
  'Udupi Thatai Murukku 340g',
  '<h3>SNACKS (Balaji)</h3>',
  'Balaji Masala Masti 150gm',
  '<h3>DRINKS (Cold Drinks Mini Glass Bottles)</h3>',
  'Thumbs Up Mini bottle 200ml',
  'Mazza mango Drink Mini bottle 200ml',
  '<h3>DRINKS (Juice)</h3>',
  'Real Mix Fruit Juice 1lt',
  '<h3>DRINKS (Lassi)</h3>',
  'Sai Shree Mango Lassi',
  '<h3>DRINKS (Milk Drink)</h3>',
  'Keshav Badam Milk 250ml',
  '<h3>DRINKS (Cold Drinks)</h3>',
  'Mazza mango Drink 600ml',
  'Thumbs Up can 300ml',
  'Limca Can 300ml',
  '<h3>BISCUITS (Bikanoo)</h3>',
  'Bikanoo Suji Rusk 600g',
  '<h3>BISCUITS (Britania)</h3>',
  'Britania Marie Gold 150g',
  'Britania Nutri Choice 150g',
  'Britania Suji Rusk 610g',
  'Britannia Cake Rusk 240g',
  'Britannia Digestive Sugar Free 200g',
  'Goodday Cashew 720g Value pack',
  'Goodday Butter 720g Value pack',
  'Goodday Cashew 75g',
  'Goodday Butter 75g',
  'Britannia Bourbon 390g',
  'Britania Maria Gold Value Pack 600gm',
  'Britania Nice Value Pack 480gm',
  '<h3>BISCUITS (Cherabs)</h3>',
  'Cherabs Almond Cookies 300gm',
  'Cherabs Besan Cookies 300gm',
  'Cherabs Butter Kaju Cookies 300gm',
  'Cherabs Cherry Cake Rusk 900Gm',
  'Cherabs Coconut Cookies 300gm',
  'Cherabs Pista Cookies 300gm',
  'Cherabs Vegeterian Atta Biscuit 1kg',
  'Cherabs Vegeterian Nankatai 300gm',
  'Cherabs Besan Nankatai 300gm',
  'Cherabs Cherry Cake Rusk 900Gm (Vegeterian)',
  '<h3>BISCUITS (Deep)</h3>',
  'Deep nankhatai 400g',
  'Deep Methi Khari 200g',
  'Deep Khari Original 400g',
  '<h3>BISCUITS (Parle)</h3>',
  'Parle G 376g',
  'Monaco Biscuits 316gm',
  'Parle Hide & Seek 412g',
  'Parle G 799g',
  '<h3>TEA/COFFEE/HEALTH DRINK (Heath Drink)</h3>',
  'Bourn Vita 500g',
  '<h3>TEA/COFFEE/HEALTH DRINK (Coffee)</h3>',
  'Bru Super Strong Coffee 500G',
  '<h3>TEA/COFFEE/HEALTH DRINK (Tea)</h3>',
  'Taj Mahal 450g',
  'Wagh Bakri 1kg',
  'Girnar Cardamom chai premix',
  'Girnar Masala Chai premix',
  'Red Label 450g',
  'Red Label Nature Care 250g',
  'Wagh Bakri Masala Tea 250g',
  'Wagh Bakri 500g',
  'Red Label 1kg',
  '<h3>READY TO EAT (Gits)</h3>',
  'Gits Gulab Jamun 500g',
  'Gits Khaman Dhokla 500g',
  'Gits Nylon Khaman 500g',
  'Gits Rava Dosa 500g',
  'Gits Rava Idli 500g',
  'Gits Dahi Vada 500g',
  'Gits Handvo 500g',
  'Gits Upma 500g',
  'Gits Medhu Vada 500g',
  'Gits Khatta Dhokla 500g',
  '<h3>READY TO EAT (Kheer Mix)</h3>',
  'Shan Badam Kheer',
  '<h3>READY TO EAT (Maggi)</h3>',
  'Maggi Masala Noodles 420g',
  'Maggi Atta Noodles 290Gm',
  '<h3>FROZEN PARATHA/NAAN/BHATURA (Bhatura)</h3>',
  'Deep Bhatura (5 pcs)',
  '<h3>FROZEN PARATHA/NAAN/BHATURA (Naan)</h3>',
  'Deep Garlic Naan (4pcs)',
  'Deep Tandoori Naan (5pcs)',
  '<h3>FROZEN PARATHA/NAAN/BHATURA (Paratha)</h3>',
  'Deep Methi Paratha(5pcs)',
  'Deep Paneer Paratha (4pcs)',
  'Haldiram Aloo Paratha 4pcs',
  'Halidiram Gobi Paratha 4pcs',
  'Haldiram Aloo Achari Paratha 4pcs',
  'Deep Mix Vegetable Paratha 4 Pcs',
  'Deep Aloo Paratha 4pcs',
  'Malabar Treat Malabar Wheat Parotta 908g',
  '<h3>FROZEN PARATHA/NAAN/BHATURA (Roti/Paratha (FAMILY PACK))</h3>',
  'Kawan Plain Paratha (25pcs)',
  'Deep Home-style Paratha Family Pack (20pcs)',
  'Katoomba Paratha (30pcs)',
  'Katoomba Wholemeal Roti Paratha(25pcs)',
  'Katoombaa Chapati 30 Pcs',
  'Kawan Chapati 30pcs',
  'Pattu Roti Paratha 30Pcs',
  'Pillsbury Microwave Roti 30 Pc',
  'Pillsbury Tava Roti 30 Pc',
  '<h3>FROZEN PARATHA/NAAN/BHATURA (Naan (Family Pack))</h3>',
  'Family pack Deep Tandoori Naan (16pcs)',
  '<h3>FROZEN SNACKS (Aloo Tikki)</h3>',
  'Haldiram Aloo tikki 420g (8pcs)',
  '<h3>FROZEN SNACKS (Kachori)</h3>',
  'Deep Moong Dal Kachori 708g(25pcs)',
  '<h3>FROZEN SNACKS (Mathia)</h3>',
  'Deep Mathia 200g',
  '<h3>FROZEN SNACKS (Muthia)</h3>',
  'Bhagwati Muthia 340g',
  '<h3>FROZEN SNACKS (Samosa)</h3>',
  'Ashoka Punjabi Samosa 1875g(25pcs)',
  'Deep Potato Cocktail Samosa 425g(50pcs)',
  'Sabrini Asli Punjabi Samosa 1.875kg(25pcs)',
  '<h3>FROZEN SNACKS (South India Specials)</h3>',
  'Udupi Idli 255g',
  'Udupi Mendu Vada 233g',
  'Udupi Masala Dosa 397g(4 Pcs)',
  'Udupi Utthapum 354g(4pcs)',
  'Udupi Sambar(283g)',
  'Deep Coconut Chutney 255g',
  'Udupi Sambhar 283g',
  '<h3>FROZEN SNACKS (Spring Roll)</h3>',
  'Hot Wok Spring Roll 255g',
  '<h3>FROZEN SNACKS (Veggie Burger Patty)</h3>',
  'DeepVegie burger 283g',
  '<h3>FROZEN FRUITS (Frozen Fruits)</h3>',
  'Chickoo Slices 312g',
  'Deep Green Mango 340g',
  'Vadilal Alphonso Mango slices 312g',
  'Vadilal Green Mango 312g',
  '<h3>CHINESE (Ajinomoto)</h3>',
  'Ajinomoto 50G',
  '<h3>CHINESE (Chutney)</h3>',
  'Chings Schezwan Chutney 250g',
  '<h3>CHINESE (Sauce)</h3>',
  'Chings Schezwan Sauce - Stir Fry',
  'Chings Chilli Vinegar 170ml',
  'Chings dark Soy Sauce 210gm',
  'Chings Green Chilli Sauce 190gm',
  'Chings Red Chilli Sauce 200gm',
  '<h3>CHINESE (Noodles)</h3>',
  'Chings Hakka Noodles 600gm',
  '<h3>PAPAD (Eastern)</h3>',
  'Eastern Plain Papad 200g',
  '<h3>PAPAD (Fryums)</h3>',
  'Bansi Color Fryums 200G',
  'Bansi Fry me 200G',
  '<h3>PAPAD (Lijjat)</h3>',
  'Lijjat Papad Orignal 200gm',
  'Lijjat Papad Jeera 200gm',
  '<h3>PICKLE/CHUTNEY/SAUCES (Chutney)</h3>',
  'Deep Tamarind Date Chutney 227g',
  'Deep Tamarind Date Chutney 510g',
  'Mirch Masala Pani Puri Concentrate 220g',
  'Pattu Sandwich Spread 280g 1+1(Free)',
  '<h3>PICKLE/CHUTNEY/SAUCES (Pickle)</h3>',
  'Deep Hot Mango Pickle 740g',
  'Priya Cut Mango Pickle300g(with garlic)',
  'Priya Mango Pickle 300g(Avakaya with garlic)',
  'Deep Sweet Lime Pickle 340g',
  'Priya Mix vegetable pickle 300g(with garlic)',
  'Deep Chundo 350g',
  'Deep Green Chilli Pickle 283g',
  '<h3>PICKLE/CHUTNEY/SAUCES (Sauce)</h3>',
  'Maggi Hot and Sweet 500g',
  'Maggi Rich Tomato 500g',
  'Pattu Chilli Garlic 500gm',
  '<h3>PASTE (Ginger/Garlic)</h3>',
  'Deeep Ging Garlic 723g',
  'Deep Garlic Paste 283Gm',
  'Deep Garlic Paste 723g',
  'Deep Ginger Garlic Paste 283Gm',
  'Deep Ginger Paste 283Gm',
  'Deep Ginger Paste 723g',
  'Katoomba Ginger Garlic Paste 1kg',
  'Katoomba Garlic Paste 1kg',
  '<h3>PASTE (Ready Paste)</h3>',
  'Larich Curry Paste 350g',
  'Bolts Curry Paste Hot 200gm',
  'Bolts Curry Paste Medium 200gm',
  'Bolts Vindaloo Paste 200gm',
  'Bolts Fish Curry Paste 200gm',
  'Bolts Tandoori Paste 200gm',
  '<h3>PEANUTS/DRYFRUITS (Cashew)</h3>',
  'Cashew Lg Pcs 250g',
  'Pattu Cashew Raw 250g',
  '<h3>PEANUTS/DRYFRUITS (Raisins)</h3>',
  'HS Raisins-Golden 250g',
  '<h3>PEANUTS/DRYFRUITS (Peanuts)</h3>',
  'Pattu Peanut blanched 250g',
  'Pattu Peanuts Raw Large 500g',
  'Pattu Peanuts Raw Lg 250g',
  'Pattu Peanuts Raw Small 1Kg',
  'Australian Peanuts Raw Large Loose (Mention QTY in Email/Message)',
  '<h3>PEANUTS/DRYFRUITS (Dates)</h3>',
  'Pattu Dates 500g',
  '<h3>SOOJI/RAVA/SAGO MORAIYA</h3>',
  'Bambinoo Vermicelli 800g',
  'Dalia 907g',
  'Deep Sooji Coarse 1.81kg',
  'Deep Sooji Coarse 907g',
  'Deep Sooji Farina 1.8kg',
  'Moraiyo 500g',
  'Shan Roasted Vermicelli 150g',
  'Merchant Spices Sooji Coarse 1kg',
  'Idli Rava 1kg',
  'Roated Sooji 1kg',
  'Sago/Sabudana 1kg',
  '<h3>PRODUCTS FROM MAHARASHTRA (Chutney,Powder,premix)</h3>',
  'Karala Chutney 100g',
  'Marathi Swad Javas Chutney 100g',
  'Marathi Swad Jeshthmadh Powder 100g',
  'Marathi Swad Vada Paav Chutney 100G',
  'Parijat Metkut 100g',
  'Bedekar Liniseed Chutney',
  'Marathi Swad Dink Powder  200g',
  '<h3>PRODUCTS FROM MAHARASHTRA (Products from MaharashtraFlour)</h3>',
  'Parijat Saguti Vade Flour 500g',
  '<h3>PRODUCTS FROM MAHARASHTRA (Flour)</h3>',
  'Sahyadri Jowar Flour 1kg',
  'Saguti Vade Flour 500G',
  'Sakas Rice Flour 1Kg',
  'Marathi Swad Kulith Pith 250G',
  'Sakas Thalipeeth Bhajani 500g',
  'Sakas Upwas Bhajani 500g',
  'Parijat Upwas Bhajani 250g',
  'Parijat Paushthik Bhakri Flour 500g',
  'Parijat Bajari Flour 500g',
  'Parijat Thalipeeth Bhajani 500g',
  'Parijat Sattu Flour 200g',
  'Parijat Infant Porridge mix 200g',
  '<h3>PRODUCTS FROM MAHARASHTRA (Frys)</h3>',
  'Crispy Kurdai  200G',
  'Nachani Papad',
  'Potato Papad Red Chili 200G',
  'Potato Salli 200g',
  'Sabudana Papadi Plain 200G',
  'Poha Mirgund 200g',
  'Crispy onion rings ',
  'Sandge',
  '<h3>PRODUCTS FROM MAHARASHTRA (Ghee)</h3>',
  'Chitale Cow ghee 1lt',
  '<h3>PRODUCTS FROM MAHARASHTRA (Masala)</h3>',
  'Sakas Kala/Goda Masala 100g',
  'Prakash Kolhapuri Bharli Vangi 25g',
  'Prakash Kolhapuri Chicken Rasa Masala 25g',
  'Prakash Misal Rassa Masala',
  'Parijat Goda masala 100g',
  'Parijat Magic masala100g',
  'Prakash Malvani Fish Rassa masala',
  'Prakash Khandeshi Masala',
  'Prakash Shev Bhaji Masala',
  'Marathi Swad Malvani Masala',
  'Marathi Swad Kanda Lasun Masala',
  'Kalyan Pani Puri Masala ',
  '<h3>PRODUCTS FROM MAHARASHTRA (Pickle)</h3>',
  'Bedekar Lime Chilli Pickle',
  'Bedekar mango pickle',
  '<h3>PRODUCTS FROM MAHARASHTRA (Pulp)</h3>',
  'Desai Bandhu Alphonso mango Pulp with Chunks(Hand made)',
  'Desai Bandhu Alphonso mango Pulp (machine made)',
  '<h3>PRODUCTS FROM MAHARASHTRA (Ready to Eat)</h3>',
  'Kalyan Misal Tarri ',
  'Devashree Ready to eat ambadi Bhaji',
  'Devashree Ready to Eat Patra Bhaji',
  'Marathi Swad Aluchi(patra) Bhaji',
  '<h3>PRODUCTS FROM MAHARASHTRA (Rice)</h3>',
  'Sahyadri Ambemohar Rice 5kg ',
  'Sahyadri Kolam  Rice 5kg',
  'Sahyadri Indrayani Rice 5kg',
  '<h3>PRODUCTS FROM MAHARASHTRA (Snacks)</h3>',
  'Sohum Udyog Rajgira roll ',
  'Ganesh Bhel 250g',
  'Kalyan Farsan',
  'Chitale Bandhu Bakarwadi ',
  'Kalyan Pani Puri',
  '<h3>PRODUCTS FROM MAHARASHTRA (Souring & Syrups)</h3>',
  'Yojak Amsul 200g',
  'Yojak Kokam Agal 500ml',
  'Yojak Kokam Syrup 500ml',
  'Yojak Kaire Panhe 500ml',
  '<h3>PRODUCTS FROM MAHARASHTRA (Sweets)</h3>',
  'Lonawala Shengdana Wadi 200g',
  'Marathi Swad Ready to Eat Puran',
  'Kalyan Ready To eat Puran',
  'Mahabaleshwar Jelly Sweet',
  '<h3>PERSONAL CARE (Beauty Products)</h3>',
  'Fair and Lovely HD Glow 80g',
  'Rose Water',
  'Shilpa Bindi black size 7',
  'Ayur Rajasthani Dark Brown Mehendi ',
  'Patanjali Saundarya Aloe Vera Gel 150ml+Free Dant Kanti toothpaste',
  'Neha Heena/Mehandi Cone',
  'Bigen N10 Oriental Black',
  'Bigen N20 Black Brown',
  'Kamill Fruit Cream Bleach 60gm',
  'Ponds white beauty Face Wash 100g',
  '<h3>PERSONAL CARE (Extra)</h3>',
  'Tongue Cleaner',
  '<h3>PERSONAL CARE (Face Wash)</h3>',
  'Ponds White Beauty face wash 100g',
  'Clean & Clear Foaming Face wash 100ml',
  '<h3>PERSONAL CARE (Hair Oil)</h3>',
  'Bajaj Almond Drops 300ml',
  'Bajaj Almond Drops 50ml',
  'Dabur Vatika Hair Oil 250ml',
  'Parachute Coconut Oil 200ml',
  'Parachute Coconut Oil 500ml',
  '<h3>PERSONAL CARE (Oil)</h3>',
  'Castor Oil 200ml',
  'Dabur Rogan Badam Oil 50ml',
  'Neem Oil 100ml',
  '<h3>PERSONAL CARE (Talcum Powder)</h3>',
  'Ponds Magic Talcum Powder 400g',
  '<h3>PERSONAL CARE (Toothpaste)</h3>',
  'Patanjali Dant Kanti toothpaste 200gm',
  'Dabur Red Toothpaste 200gm',
  '<h3>PERSONAL CARE (Washing Powder)</h3>',
  'Surf Excel 500gm',
  '<h3>RICE,POHA,MURMURA (Murmura)</h3>',
  'Bansi Murmura 400g',
  '<h3>RICE,POHA,MURMURA (Poha)</h3>',
  'Bansi Poha Medium 1.81kg',
  'Bansi Poha Thick 907g',
  'Deep Poha Super Thin 907g',
  'Deep Poha Super Thin 1.81kg',
  'Deep Poha Thin(Medium)907g',
  'Xilllent Poha Thin(Nylon) 1 kg',
  '<h3>RICE,POHA,MURMURA (Sona Masoori)</h3>',
  'Balaji Sona Masoori 5kg',
  'India Gate Sona Masoori 5kg',
  '<h3>RICE,POHA,MURMURA (Basmati)</h3>',
  'India Gate Basmati Classic Rice 5kg',
  'India Gate Basmati Super 5Kg',
  'Xillent Basmati Rice 5Kg',
  'Har Roz Basmati Rice 5kg',
  'Freshco Basmati Everday Rice 5kg',
  'Freshco extra long grain basmati Rice 5kg',
  'Dawaat Biryani Basmati Rice 5kg',
  'India Gate Sona Masoori 25kg',
  '<h3>RICE,POHA,MURMURA (Red Rice)</h3>',
  'HS Red Rice 5kg',
  '<h3>RICE,POHA,MURMURA (Idli Rice)</h3>',
  'Balaji Idli Rice 5kg',
  '<h3>RICE,POHA,MURMURA (Ponni)</h3>',
  'Ponni Rice 5kg',
  'Ponni Parboiled Rice 5kg',
  '<h3>RICE,POHA,MURMURA (Sells Basmati)</h3>',
  'India Gate Sella White Basmati Rice 5kg ',
  'India Gate Sella Golden Basmati Rice 5kg',
  '<h3>RICE,POHA,MURMURA (Basmati (1kg))</h3>',
  'Daawat Biryani 1Kg',
  '<h3>RICE,POHA,MURMURA (Brown Rice(1kg))</h3>',
  'Daawat Brown Rice 1Kg',
  '<h3>GHEE/OIL (Ghee)</h3>',
  'Britannia Cow Ghee 902g',
  'Deep Cow Ghee 946ml',
  'Verka Ghee 1Lt',
  'Chitale ghee 1Lt',
  'Grewal Ghee 4 lt',
  'Pure New Zealand Ghee 1.8Lt',
  '<h3>GHEE/OIL (Oil)</h3>',
  'Nanki Mustard oil 500ml',
  'Millers Sunflower Oil 5lts',
  'Dhara Vegetable Oil 2lts',
  'Dhara Sunflower Oil 2lts',
  'Idhyam Sesame/Gingelly  Oil 2lts',
  'Ishwar Mustard Oil 1lt',
  '<h3>DAIRY/PANEER (Amrakhand)</h3>',
  'Sai Shree Amrakhand 270g',
  '<h3>DAIRY/PANEER (Khoa)</h3>',
  'Nanak Khoa',
  '<h3>DAIRY/PANEER (Paneer)</h3>',
  'Nanak Malai paneer cubes 400g',
  'Nanak Paneer Cubes fried 400g',
  'Sai Shree Paneer (Average block of 300gms)',
  'Sharmas Paneer (Average block of 300gms)',
  'Village Paneer (Average block of 300gms)',
  '<h3>DAIRY/PANEER (Shrikhand)</h3>',
  'Sai Shree Shrikhand 270g',
  '<h3>DAIRY/PANEER (Yoghurt)</h3>',
  'Sai Shree Yoghurt 1kg',
  'Village pot set Yoghurt 2kg',
  'Village organic Yoghurt 2kg',
  'Village Pot set Yoghurt 5kg',
  'Sai Shree Yoghurt 5kg',
  'Sharmas Yoghurt 2kg',
  '<h3>IDLI BATTER (Idli Batter)</h3>',
  'Keshav Idli Batter 1kg',
  'Sai Shree Idli Dosa Batter 1kg',
  'Sai Shree Idli Dosa Batter 2kg',
  '<h3>COCONUT (Dry Coconut)</h3>',
  'Coconut Dessicated-Fine 500gm',
  'Coconut Slice 200gm',
  'Coconut Half 170g',
  '<h3>SPICES (Chilli Powder)</h3>',
  'Pattu Kashmiri Chilli Pdr 500g',
  'Katoomba Red Chilli Powder (Xtra Hot) 500g',
  '<h3>SPICES (Chilli Whole)</h3>',
  'Pattu Chilly Round 200g',
  'Eastern Kashmiri Chilli 100g',
  'Eastern Red Chilli Hottest 100g',
  '<h3>SPICES (Everest)</h3>',
  'Everest Chole Masala',
  'Everest Kitchen King 100g',
  'Everest Sambhar Masala',
  'Everest Shahi Paneer Masala  100g',
  'Everest Royal Garam Masala 100g',
  'Everest Sabji Masala 100g',
  'Everest Pani Puri Masala 100g',
  '<h3>SPICES (Fried Onion)</h3>',
  'Mothers Fried Onion Flakes 400g',
  '<h3>SPICES (Garam Masala)</h3>',
  'Deep Garam Masala 200Gm',
  'Deep Garam Masala 400g',
  'Deep Garam Masala 800Gm',
  'Shan Seekh Kebab Masala',
  '<h3>SPICES (Mangal)</h3>',
  'Mangal Rajma Masala',
  'Mangal Tandoori Masala',
  'Mangal Vindaloo Masala',
  '<h3>SPICES (MDH)</h3>',
  'MDH Chat masala 100g',
  'MDH Deggi Mirch Powder 100g',
  'MDH Pav Bhaji Masala 100g',
  'MDH Garam Masala 100g',
  'MDH Kasoori Methi 25g',
  'MDH Tea masala 35g',
  '<h3>SPICES (Other Powder Spices)</h3>',
  'Curry Powder Unroasted 500g',
  'Cuury powder-Jafna 500g',
  'Galangal 100g',
  '<h3>SPICES (Powder Spices)</h3>',
  'Deep Spi Cardamom Powder 100g',
  'Deep Spi Cinnamon Powder 100Gm',
  'Deep Spi Coriander Cumin powder 400g',
  'Deep Spi Coriander Cumin Powder 800G',
  'Deep Spi Cumin Powder 200g',
  'Deep Turmeric Powder 200Gm',
  'Deep Turmeric Powder 400Gm',
  'Mace Powder 100Gm',
  'Pattu Amchur Powder 100g',
  'Pattu Coriander Powder 100g',
  'Pattu Coriander Powder 500g',
  'Pattu Nutmeg Powder 100g',
  'White Pepper Powder 100Gm',
  'Deep Ginger Powder200Gm',
  '<h3>SPICES (Shan)</h3>',
  'Shan Chana Masala',
  'Shan Chicken Masala',
  'Shan Chicken Tikka Masala',
  'Shan Curry Powder',
  'Shan Fried Chops/Steak Masala',
  'Shan Haleem Masala',
  'Shan Karahi Masala',
  'Shan Korma Masala',
  'Shan Nihari Masala',
  'Shan Bihari Kebab masala',
  'Shan Biryani Masala',
  'Shan Butter Chicken Masala',
  'Shan Chapli Kebab Masala ',
  'Shan Chicken Tandori Masala',
  'Shan Keema Masala',
  'Shan Malay Biryani Masala',
  'Shan Punjabi Yakhni Pilau Masala',
  'Shan Seekh Kebab Masala',
  'Shan Bombay Biryani Masala',
  '<h3>SPICES (Whole Spices)</h3>',
  'Deep Black Cardomom 100gm',
  'Deep Cumin Powder 400g',
  'Deep Grn Cardamom Whl200Gm',
  'Deep Mustard Seed 400g',
  'Deep Sesame Seeds 200Gm',
  'Deep Spi Black Pepper Whl 400Gm',
  'Deep Spi Cinnamon Stick 200G',
  'Deep Spi Cumin Seeds 200Gm',
  'Deep Spi Green Cardamom Whole 100Gm',
  'Deep Spi Mustard Seeds 200Gm',
  'Deep whole Garam Masala 200g',
  'HS Star Annise Whole 100g',
  'Katri Gum 100Gm',
  'Panch Phoran 100g',
  'Pattu Ajwain Seeds 100g',
  'Pattu Bay Leaves 100g',
  'Pattu Cloves Whole 100Gm',
  'Pattu Fennel Seeds 100g',
  'Pattu Fennel Seeds 200g',
  'Pattu Fenugreek seeds 100g',
  'Pattu Fenugreek Seeds 200g',
  'Pattu Poppy seesds white 100g',
  'Pattu Sesame seedes white 250g',
  'Pattu Shah Jeera 100Gm',
  'Coriander Seeds 400g',
  'Cummin Seeds 250g',
  'Kali Jeeri 100g',
  'Cummin Seeds 1kg',
  'Pattu Black Pepper 200g',
  'Cummin Seeds 200g',
  'Cummin Seeds 400G',
  '<h3>SALT/SUGAR MICELLANEOUS (Baking)</h3>',
  'Baking Powder 150g',
  'Bi Crab Soda 150gm',
  '<h3>SALT/SUGAR MICELLANEOUS (Essence)</h3>',
  'Kewra Essence 25ml',
  'Pineapple Essence 25ml',
  '<h3>SALT/SUGAR MICELLANEOUS (Food Color)</h3>',
  'HS Saffron Food Color 50g',
  'HS Tandoori Color',
  '<h3>SALT/SUGAR MICELLANEOUS (Hing)</h3>',
  'LG Hing 50g',
  'Vandevi Hing 50g',
  'LG Hing 100g',
  '<h3>SALT/SUGAR MICELLANEOUS (Honey)</h3>',
  'Dabur Honey 300g',
  '<h3>SALT/SUGAR MICELLANEOUS (Jaggery)</h3>',
  'Kozhi Kodens Jaggery Powder 1kg',
  'Udupi Jaggery Powder 454g',
  'Punjabi Gur 907g',
  'MT Round Jaggery 1kg',
  'Xillent Kolhapuri Jaggery 1Kg',
  '<h3>SALT/SUGAR MICELLANEOUS (Kokum)</h3>',
  'Black Kokum 400g',
  '<h3>SALT/SUGAR MICELLANEOUS (Mouth Freshner)</h3>',
  'Chandan mix mouthfreshner 6 in 1 230gm',
  '<h3>SALT/SUGAR MICELLANEOUS (Saffron)</h3>',
  'Kashmiri Saffron',
  '<h3>SALT/SUGAR MICELLANEOUS (Salt(Fasting))</h3>',
  'Sendhav Salt 100g(Upwas)',
  '<h3>SALT/SUGAR MICELLANEOUS (Salt)</h3>',
  'Tata Salt 1kg',
  'Black Salt Powder 100g',
  'Tata Salt 2kg',
  'Tata Salt 1kg Lite',
  '<h3>SALT/SUGAR MICELLANEOUS (Sugar)</h3>',
  'Raw Sugar 1kg',
  'Brown Sugar 1kg',
  'Pattu Sugar White 1kg',
  '<h3>SALT/SUGAR MICELLANEOUS (Tamarind)</h3>',
  'Tamarind Concentrate 227Gm',
  'Tamarind Seedless',
  '<h3>SALT/SUGAR MICELLANEOUS (Tutti Frutti)</h3>',
  'Tutti Frutti 200gm',
  '<h3>FROZEN VEGETABLES (Coconut)</h3>',
  'Deep Premium Coconut slices 340g',
  'Sunfeast Grated coconut 400g',
  'Vadilal Grated coconut 340g',
  '<h3>FROZEN VEGETABLES (Veggies)</h3>',
  'Deep Arvi 340g',
  'Deep Drumsticks 340g',
  'Deep Dudhi 340g',
  'Deep Green Peas 907g',
  'Deep Karela 340g',
  'Deep Methi 340g',
  'Deep Suran 340g',
  'Vadilal Amla 312g',
  'Vadilal Avial Mix',
  'Vadilal Cassava Cuts 312g',
  'Vadilal Chauli String Beans 312g',
  'Vadilal Ratalu 312g',
  'Vadilal Kala Chana 312g',
  'Vadilal Moth Beans 312g',
  'Deep Sambhar Mix 340g',
  'Deep Surti Undhiu Mix 340g',
  'Deep Parwal 340g',
  'Deep Punjabi Tinda 340g',
  'Deep Tindora 340g',
  'Deep Bhindi Cut(Okra) 340g',
  'Deep Baby Bhindi 340g',
  'Deep Red Pearl Onion 340g',
  'Vadilal Green chillies 312g 10% extra',
  '<h3>PULSES (Deep/Pattu/Xillent/Parsram Sahej/Katoomba)</h3>',
  'Chick Peas Kabuli 1Kg',
  'Masoor Gota 1kg',
  'Roasted Channa 400Gm',
  'Roasted Gram Split 1kg',
  'Yellow Split Peas 1Kg',
  'Masoor daal 907g',
  'Moong Dal 907Gm',
  'Moong Dal Chilka 907G',
  'Urad Daal 907g',
  'Urad Dal Chilka 907g',
  'Masoor Whole 1kg',
  'Toor Daal 1kg',
  'Urad Gota 1kg',
  'Tyson Chick Pea 1kg',
  'Moth Beans 907g',
  'Black Eye Beans 1kg(Lobia) 1kg',
  'Red Kidney Beans Dark 1kg (Rajma)',
  'Red Kidney Bean Light 1kg',
  'Moong Beans Berken 1kg(whole)',
  'Soya Granules 200g',
  'Soya chunks mini 200g',
  'Soya wadi 200g',
  'Urad whole black 1kg',
  'Chick Peas Kabuli 2kg',
  'Nutrela Soy Chunks 1Kg',
  'Chick Pea Large ord river 1kg',
  'Cranberry Beans 1kg',
  '<h3>ATTA/FLOUR (Flour Variety(Fasting Flour))</h3>',
  'Deep Kuttu Flour 907g(upwas)',
  'Deep Singora flour 907g(upwas)',
  '<h3>ATTA/FLOUR (Flour Variety)</h3>',
  'Deep Bajari Flour 907g',
  'Deep Bhakri Flour 907g',
  'Deep Dhokla Flour 907g',
  'Deep Jowar Flour 907g',
  'Deep Ladu Besan 907g',
  'Deep Maida 907g',
  'Deep Rice Flour 907g',
  'Grewal Besan 1kg',
  'Deep Besan 907g',
  'Merchant Spices Maida 1kg',
  'Merchant Spice Rice Flour 1kg',
  'Grewal Makki Atta 1kg',
  '<h3>ATTA/FLOUR (Parijat)</h3>',
  'Parijat Bhakri Flour 500gm',
  '<h3>ATTA/FLOUR (Wheat Atta/Flour)</h3>',
  'Pilsbury Gold Atta 10kg',
  'Grewal Chakki Atta 5kg',
  'Aashirwad Chakki Atta 5Kg',
  'Pilsbury Chakki Atta 10Kg',
  'Pilsbury Chakki Atta 5Kg',
  'Pilsbury Gold Atta 5kg',
  'Soham Udyog Lokwan Atta 5kg',
  'Grewal Chakki Atta 10Kg',
  'Aashirwad Chakki Atta 10kg',
  'Aashirwad Select 10kg',
  'Aashirwad Select 5kg',
  '<h3>ATTA/FLOUR (Wholemeal Atta/Flour)</h3>',
  'Grewal Wholemeal Atta 10kg',
  '<h3>ATTA/FLOUR (Multigrain)</h3>',
  'Pilsbury Multigrain 5kg',
  '<h3>SWEETS</h3>',
  'Haldiram Gulab Jamun 1kg',
  'Haldiram Rasgulla 1kg',
  'Nanak Kalakand 400g',
  'Chitale Bandhu Soan Papdi(Mango)200g',
  'Chitale Bandhu Soan Papdi(Orange) 200g',
  'Keshav Motichoor Laddu 260g',
  'Deep Kesar Mango Pulp',
  'Bikanoo Besan ladoo 400gm',
  'Nanak Kaju Katli 255g',
  'Nanak Rasmalai 1 kg',
  'Aam Papad 90g',
  '<h3>MEDICINE (Cough/Cold)</h3>',
  'Dabur Honitus 100ml',
  'Vicks Vaporub 50ml',
  '<h3>MEDICINE (Overall)</h3>',
  'Himalaya Liv 52 Syrup',
  '<h3>MEDICINE (Stomach)</h3>',
  'Kayamchurna 100g',
  'Dabur Pudin Hara 30ml',
  'Dabur Triphala Churna 120g',
  'Dabur Hajmola 100gm',
  'Eno Regular 100gm',
  '<h3>MEDICINE (Energy)</h3>',
  'Glucon-D 100',
  'Dabur Shilajit',
  '<h3>MEDICINE (Kids)</h3>',
  'Woodwards Gripe Water 130ml',
  '<h3>POOJA (Agarbatti)</h3>',
  'Hem 5 agarbatti',
  'Hem Gulab Agarbatti',
  'Hem Lavendar agarbatti',
  'Hem Love Agarbatti',
  'Hem Meditation Agarbatti',
  'Hem Mogra Agarbatti',
  'Hem Rose musk',
  'Hem White Musk',
  'Hem Fragrance Agarbatti',
  '<h3>POOJA (Bhagwan)</h3>',
  'Cotton Wicks',
  'Gnapati Pooja samagri set',
  'Sehaj White Janeu',
  'Vibhuti pooja item',
  '<h3>POOJA (Dhoop)</h3>',
  'Vinayak Sandal Dhoop',
  'Vinayak Rose Dhoop',
];
